from pydantic import BaseModel, Field
from typing import Dict, List, Optional, Any, Union

class ModelConfig(BaseModel):
    """Configuration for calling a model endpoint or loading a local Hugging Face model."""
    backend: str = Field(default="api", description="Backend type: 'api' (OpenAI endpoint) or 'hf' (local Hugging Face transformers)")
    api_url: str = Field(default="http://localhost:8000/v1", description="URL to the OpenAI-compatible API endpoint (for api backend)")
    model_name: str = Field(default="", description="Name of the model or HF repository ID (e.g. Qwen/Qwen3.6-27B)")
    device_map: str = Field(default="auto", description="Device mapping strategy for HF backend (e.g. 'auto', 'cuda:0', 'cpu')")
    torch_dtype: str = Field(default="bfloat16", description="Torch dtype for HF backend (e.g. 'bfloat16', 'float16', 'float32')")
    temperature: Optional[float] = Field(default=None, ge=0.0, le=2.0, description="Temperature for generation (recommend 0.0 for judges)")
    max_tokens: int = Field(default=1024, description="Maximum number of tokens to generate")
    steering: Optional[Dict[str, float]] = Field(default=None, description="Dynamic steering vector overrides for steerable-model-runner (for api backend)")
    headers: Optional[Dict[str, str]] = Field(default=None, description="Custom HTTP headers (e.g., Authorization: Bearer ...) (for api backend)")
    api_key: Optional[str] = Field(default=None, description="API key for authentication (defaults to OPENAI_API_KEY environment variable if not specified) (for api backend)")

class EvalRecord(BaseModel):
    """Representing a single source record to be evaluated."""
    id: str = Field(description="Unique identifier for the evaluation record")
    prompt: str = Field(description="The input query / prompt sent to the model under test")
    context: Optional[str] = Field(default=None, description="Optional supporting context/document context for the prompt")
    reference: Optional[str] = Field(default=None, description="Optional reference / ground truth answer")
    expected_group: Optional[str] = Field(default=None, description="Optional target class/group for classification tasks")
    completion: Optional[str] = Field(default=None, description="The model generation under test (if already generated)")
    completions: Optional[Dict[str, str]] = Field(
        default=None, 
        description="Dictionary mapping completion identifiers (e.g. steering settings) to completion texts"
    )
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Arbitrary metadata dictionary")

class EvalResult(BaseModel):
    """The result of a single judgment."""
    record_id: str = Field(description="The ID of the EvalRecord being judged")
    task_type: str = Field(description="The evaluation task type: classification, ranking, scoring, or pairwise")
    reasoning: str = Field(description="The reasoning trace generated by the judge model")
    judgement: Any = Field(description="The parsed judgment output (e.g., class label, ranking list, numerical score)")
    raw_response: str = Field(description="The raw output text returned by the judge LLM")
    expected_group: Optional[str] = Field(default=None, description="The expected class label (copied from record if available)")
    completion_id: Optional[str] = Field(default=None, description="The identifier of the specific completion evaluated (if multiple exist)")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Extra metadata associated with the evaluation")

class SummaryMetrics(BaseModel):
    """Summarized metrics across all evaluated records."""
    task_type: str = Field(description="The task type evaluated")
    total_records: int = Field(description="Total number of evaluated records")
    metrics: Dict[str, Any] = Field(description="Computed metric statistics (e.g., accuracy, win_rates, average_score)")
